config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :usuarios
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contato.rb
class Contato < ApplicationRecord
  belongs_to :usuario
end

app/models/genero.rb
class Genero < ApplicationRecord
    has_many :usuario
end

app/models/usuario.rb
class Usuario < ApplicationRecord
  belongs_to :genero

  validates :nome, :datanascimento, :cpf, :genero_id, presence:true
  validates :cpf, uniqueness: true

  has_many :contatos, dependent: :destroy
  accepts_nested_attributes_for :contatos, reject_if: :all_blank, allow_destroy: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/usuarios_controller.rb
class UsuariosController < ApplicationController

#index / show / edit / update / new / create / destroy

    def index
        @usuarios = Usuario.all
        @usuario = Usuario.new
    end

    def show
        @usuario = Usuario.find(params[:id])
    end

    def edit
        @usuario = Usuario.find(params[:id])
    end
    
    def update
        @usuario = Usuario.find(params[:id])
        @usuario.update(usuario_params)
        redirect_to usuarios_url
    end
    
    def destroy
        @usuario = Usuario.find(params[:id])
        @usuario.destroy
        redirect_to usuarios_url
    end

    def create
        @usuario = Usuario.new(usuario_params)
        @usuario.save
        redirect_to @usuario
    end

    private 
    def usuario_params
        params.require(:usuario).permit(:nome, :datanascimento, :cpf, :genero_id, 
        contatos_attributes: [:id, :numero, :tipo, :_destroy])
    end
      
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/usuarios_helper.rb
module UsuariosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Projetocrud</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/usuarios/_contato_fields.html.erb
<div class="nested-fields">
    <div class="row form-group">
        <div class="col field">
            <%= f.label :tipo_de_Contato%><br>
            <%= f.select :tipo, ["Residencial","Celular pessoal","Celular corporativo"]%>
        </div>

        <div class="col field">
            <%= f.label :Número%><br>
            <%= f.text_field :numero, :class=>'form-control', placeholder: "Digite o número",'data-mask': '(00)00000-0000'%>
        </div>
        
        <div class="col field">
            <div id="contatos" class="btn field" style="background-color: #08374F; margin-top: 1.9rem;">
            <%= link_to_remove_association('Remover Contato', f)%>
        </div>
    </div>

</div>

app/views/usuarios/edit.html.erb
<!DOCTYPE html>
<html lang="pt-BR">

<head>
    <!-- Metatags -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="author" content="Rodrigo Amaral">
    <meta name="description" content="Site especializado para estudos de CRUD com usuários para a empresa TotalIP">
    <title>ProjetoCRUD</title>

    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@5.15.3/css/fontawesome.min.css">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

    <!-- Scripts -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

    <!-- CSS / JS locais-->
    <link rel="stylesheet" href="../../assets/stylesheets/css/sheets.css">
</head>

<body>
    <header class="navbar navbar-expand-lg fixed-top" style="background-color:#5A4272; opacity: 0.96; min-height: 3.3rem;">
        <div id="header-navbar" class="content">

            <a href=# id="logototal" class=icons><%= image_tag 'icons/totalip.png'%></a>
            <div id="header-menu">
                <a href="http://localhost:3000/usuarios">HOME</a> |
                <a href="#">SOBRE</a> |
                <a href="#">PORTFOLIO</a> |
                <a href="#">CONTATO</a>
            </div>
            <div class="searchbox">
                <div id="searchicon" class=icons><%= image_tag 'icons/search.png'%></div>
                <input type="text" name="">
            </div>
        </div>
    </header>

    <div id="AtualizarUsuario" style="text-align: center; min-height: 2.5rem; background-color:#08374F;">
        <a href="#"><%= image_tag 'titles/TituloAtualizarUsuarios'%></a>
    </div>

    <div style="padding: 1rem 0;">

        <%=form_for(@usuario) do |f|%>
            <div id="formularios" class="form-group" style="color:#08374F; min-height: 23rem; max-width: 650px; margin: auto; padding: 2rem 0;">
                <p>
                    <%= f.label :Nome_de_Usuário%><br>
                    <%= f.text_field :nome, :class=>'form-control', placeholder: "Digite o nome de Usuário"%>
                </p>

                <div class="row form-group">
                    <div class="col">
                        <%= f.label :Data_de_Nascimento%>
                        <%= f.text_field :datanascimento, :class=>'form-control', type:"date"%>
                    </div>

                    <div class="col">
                        <%= f.label :CPF%>
                        <%= f.text_field :cpf, :class=>'form-control', placeholder: "Digite o CPF do Usuário"%>
                    </div>
                </div>

                <div style="margin-bottom: 1rem;">
                    <%= f.label :Gênero%><br>
                    <%= f.collection_select(:genero_id, Genero.all, :id, :gen, prompt: true, class:'form-control')%>
                </div>

                <div id="contatos">
                        <%= f.fields_for :contatos do |contatos_fields|%>
                        <%= render partial: "contato_fields", locals: { f: contatos_fields}%>
                    <% end %>
                    <div class="btn" style=" background-color: #08374F; margin-bottom: 2rem;">
                        <%= link_to_add_association('Adicionar Telefone', f, :contatos)%>
                    </div>
                </div>

                <div>
                    <%= f.submit 'Atualizar Dados', class:"btn", style:"background-color: #F9B443"%>
                </div>

            </div>
            <% end %>
        </div>
    </div>

    <footer style="color: white; text-align: center;">
        <div id="menuObrigado" style="min-height: 2.5rem; background-color:#604978;">
            <a href=""><%= image_tag 'titles/TituloObrigado.png'%></a>
        </div>
        <div style="background-color: #303031; padding: 1rem 0 0.1rem 0;">
            <a href=# id="logototal" class=icons><%= image_tag 'icons/totalip.png'%></a>
            <p style="padding-top: 0.5rem;">Desenvolvido por Rodrigo Vinícius Amaral</p>
        </div>

    </footer>

</body>

</html>

app/views/usuarios/index.html.erb
<!DOCTYPE html>
<html lang="pt-BR">

<head>
   
</head>

<body>
    <header class="navbar navbar-expand-lg fixed-top" style="background-color:#5A4272; opacity: 0.96; min-height: 3.3rem;">
        <div id="header-navbar" class="content">

            <a href=# id="logototal" class=icons><%= image_tag 'icons/totalip.png'%></a>
            <div id="header-menu">
                <a href="#">HOME</a> |
                <a href="#">SOBRE</a> |
                <a href="#">PORTFOLIO</a> |
                <a href="#">CONTATO</a>
            </div>
            <div class="searchbox">
                <div id="searchicon" class=icons><%= image_tag 'icons/search.png'%></div>
                <input type="text" name="">
            </div>
        </div>
    </header>

    <main>
        <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
            <ol class="carousel-indicators">
                <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
            </ol>
            <div class="carousel-inner">
                <div class="carousel-item active">
                    <%= image_tag 'banners/banner1.jpg', class: 'd-block w-100', alt: "..."%>
                </div>
                <div class="carousel-item">
                <%= image_tag 'banners/banner2.jpg', class: 'd-block w-100', alt: "..."%>
                </div>
            </div>
            <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="sr-only">Next</span>

            </a>
        </div>
    </main>
    <div id="divisoria" style="min-height: 1rem; background-color:#303031;"></div>

    <div id="consultaCRUD" style="color: white;">
        <div id="menuUsuarios" style="text-align: center; min-height: 2.5rem; background-color:#08374F;">
            <a href="#"><%= image_tag 'titles/TituloUsuarios.png'%></a>
            <div id="menuAbas" class="content" style= "padding-top: 0.5rem;">
                <button id="abaCriar" type="button" class="abas" data-toggle="collapse" data-target="#collapseCriar" aria-expanded="false" aria-controls="collapseCriar">Criar Usuário</button> |
                <button id="abaListar" class="abas"  data-toggle="collapse" data-target="#collapseListar" aria-expanded="false" aria-controls="collapseListar">Listar Usuários</button>
            </div>
        </div>

        <div class="formContainer" style="color: white; font-weight: 700; min-height: 4rem;">

            <div class="collapse" id="collapseCriar">

                <%=form_for(@usuario) do |f|%>
                    <div id="formularios" class="form-group" style="color:#08374F; max-width: 650px; margin: auto; padding: 2rem 0;">
                        <p>
                            <%= f.label :Nome_de_Usuário%><br>
                            <%=f.text_field :nome, :class=>'form-control', placeholder: "Digite o nome de Usuário"%>
                        </p>

                        <div class="row form-group">
                            <div class="col">
                                <%= f.label :Data_de_Nascimento%>
                                <%= f.text_field :datanascimento, :class=>'form-control', type:"date"%>
                            </div>

                            <div class="col">
                                <%= f.label :CPF%>
                                <%= f.text_field :cpf, :class=>'form-control', placeholder: "Digite o CPF do Usuário",'data-mask': '000.000.000-00'%>
                            </div>
                        </div>

                        <div style="margin-bottom: 1rem;">
                            <%= f.label :Gênero%><br>
                            <%= f.collection_select(:genero_id, Genero.all, :id, :gen, prompt: true, class:'form-control')%>
                        </div>

                        <div id="contatos" class="btn" style=" background-color: #08374F">
                            <%= f.fields_for :contatos do |contatos_fields|%>
                                <%= render partial: "contato_fields", locals: { f: contatos_fields}%>
                            <% end %>
                            <%= link_to_add_association('Adicionar Telefone', f, :contatos)%>
                        </div>

                        <div>
                            <%= f.submit 'Criar Usuário', class:"btn", style:"background-color: #F9B443"%>
                        </div>
                <% end %>

            </div>

        </div>

        <div class="collapse" id="collapseListar">
            <div class="card card-body">
                <div id="tabelas" style="color:#08374F; margin: auto;">
                    <table class="table" style="color:#08374F">
                        <thead>
                            <tr>
                                <th>ID</th>
                                <th>Nome</th>
                                <th>Data de Nascimento</th>
                                <th>CPF</th>
                                <th>Gênero</th>
                            </tr>
                        </thead>

                        <tbody>
                            <% @usuarios.each do |usuario| %>
                                <tr>
                                    <td><%= link_to usuario.id, usuario_path(usuario)%></td>
                                    <td><%= usuario.nome%></td>
                                    <td><%= usuario.datanascimento%></td>
                                    <td><%= usuario.cpf%></td>
                                    <td><%= usuario.genero.gen%></td>
                                </tr>
                            <% end %>
                        </tbody>

                    </table>
                </div>
            </div>
        </div>

    </div>

    <footer style="text-align: center;">
        <div id="menuObrigado" style="min-height: 2.5rem; background-color:#604978;">
            <a href=""><%= image_tag 'titles/TituloObrigado.png'%></a>
        </div>
        <div style="background-color: #303031; padding: 1rem 0 0.1rem 0;">
            <a href=# id="logototal" class=icons><%= image_tag 'icons/totalip.png'%></a>
            <p style="padding-top: 0.5rem;">Desenvolvido por Rodrigo Vinícius Amaral</p>
        </div>
    </footer>
</body>

</html>

app/views/usuarios/show.html.erb
<!DOCTYPE html>
<html lang="pt-BR">

<head>
    <!-- Metatags -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="author" content="Rodrigo Amaral">
    <meta name="description" content="Site especializado para estudos de CRUD com usuários para a empresa TotalIP">
    <title>ProjetoCRUD</title>

    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@5.15.3/css/fontawesome.min.css">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

    <!-- Scripts -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    
    <!-- CSS / JS locais-->
    <link rel="stylesheet" href="../../assets/stylesheets/css/sheets.css">
</head>

<body>
    <header class="navbar navbar-expand-lg fixed-top" style="background-color:#5A4272; opacity: 0.96; min-height: 3.3rem;">
        <div id="header-navbar" class="content">

            <a href=# id="logototal" class=icons><%= image_tag 'icons/totalip.png'%></a>
            <div id="header-menu">
                <a href="http://localhost:3000/usuarios">HOME</a> |
                <a href="#">SOBRE</a> |
                <a href="#">PORTFOLIO</a> |
                <a href="#">CONTATO</a>
            </div>
            <div class="searchbox">
                <div id="searchicon" class=icons><%= image_tag 'icons/search.png'%></div>
                <input type="text" name="">
            </div>
        </div>
    </header>

    <div id="ConsultaUsuario" style="text-align: center; min-height: 2.5rem; background-color:#08374F;">
        <a href="#"><%= image_tag 'titles/TituloInformacoesUsuarios.png'%></a>
    </div>
    
    <div style="min-height: 25.6rem; padding: 1rem 0;">
        <table class="table" style="max-width: 400px; margin: auto; border: solid #DEE2E6; text-align: center; font-size: 0.9rem;">
            <thead>
                <tr>
                    <th id="Tinfo">ID:</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td><%= @usuario.id%></td>
                </tr>
            </tbody>

            <thead>
                <tr>
                    <th id="Tinfo">Nome Completo:</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td><%= @usuario.nome%></td>
                </tr>
            </tbody>

            <thead>
                <tr>
                    <th id="Tinfo">Data de Nascimento:</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td><%= @usuario.datanascimento%></td>
                </tr>
            </tbody>

            <thead>
                <tr>
                    <th id="Tinfo">CPF:</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td><%= @usuario.cpf%></td>
                </tr>
            </tbody>

            <thead>
                <tr>
                    <th id="Tinfo">Gênero:</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td><%= @usuario.genero.gen%></td>
                </tr>
            </tbody>

            <thead>
                <tr>
                    <th id="Tinfo">Telefones:</th>
                </tr>
            </thead>

            <tbody>
                <td style="text-align: left;">
                    <% @usuario.contatos.each do |f| %>
                        <ul type="none">
                            <li style="font-weight: 700;">Tipo: <%= f.tipo %></li>
                            <li>Número: <%= f.numero %><li>
                        </ul>
                    <% end %>
                </td>
            </tbody>

        </table>

    </div>

    <div id="ConsultaUsuario" style="min-height: 3rem; background-color:#08374F;">
        <div style="max-width: 450px; margin:auto; padding-left: 1.4rem;">
            <a href="http://localhost:3000/usuarios" class="btn" style="color: white; background-color: #604978;">Voltar ao Home</a>
            <%=link_to 'Editar Usuário', edit_usuario_path(@usuario), class:"btn", style:"background-color: white"%>
            <%= link_to 'Deletar usuário', (@usuario), class:"btn", style:"background-color: #F9B443;", method: :delete, data:{confirm: "Deseja deletar este usuário?"}%>
        </div>
    </div>

    <footer style="color: white; text-align: center;">
        <div id="menuObrigado" style="min-height: 2.5rem; background-color:#604978;">
            <a href=""><%= image_tag 'titles/TituloObrigado.png'%></a>
        </div>
        <div style="background-color: #303031; padding: 1rem 0 0.1rem 0;">
            <a href=# id="logototal" class=icons><%= image_tag 'icons/totalip.png'%></a>
            <p style="padding-top: 0.5rem;">Desenvolvido por Rodrigo Vinícius Amaral</p>
        </div>
    </footer>

</body>